### ISSUE TITLE
Reward calculation

### ISSUE THREAD

**Issue by baochenfu** [video-language-planning/vlp_code#4]
Hello, I have a question. My task is to push all the blocks in the language-table environment to the bottom right corner, but I see in your code that you reward 0.125（reward += 0.125） whenever a block is in the specified position. So if there are already 7 blocks executed, the reward for the 8th block operation in each step would be 0.875, and if the reward for each step is added together, the reward value would be very high. By the time I got to step 500th, the reward was already up to 200.I'm not sure if my understanding is correct, I look forward to communicating with you.

**Comment by yilundu** [comment]
Hi, we don’t add the rewards — rather we take the max value.

**Comment by fubaochen** [comment]
I don't know how your VLP reward is calculated to be 87.3, is it the maximum value taken?



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/09/2024 18:38 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [video-language-planning/vlp_code] Reward calculation (Issue #4) |

Hi, we don’t add the rewards — rather we take the max value.

**Comment by yilundu** [comment]
You compute the max returned value per episode and then average that value across 100 environment evaluations multiplied by 100.

**Comment by fubaochen** [comment]
Thank you so much.





---- Replied Message ----
| From | ***@***.***> |
| Date | 11/10/2024 03:48 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [video-language-planning/vlp_code] Reward calculation (Issue #4) |

You compute the max returned value per episode and then average that value across 100 environment evaluations multiplied by 100.
